// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalClean.Architecture.Web.Infrastructure.Data;

#nullable disable

namespace MinimalClean.Architecture.Web.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MinimalClean.Architecture.Web.Domain.CartAggregate.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("MinimalClean.Architecture.Web.Domain.CartAggregate.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.ToTable("CartItems", (string)null);
                });

            modelBuilder.Entity("MinimalClean.Architecture.Web.Domain.GuestUserAggregate.GuestUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("GuestUsers");
                });

            modelBuilder.Entity("MinimalClean.Architecture.Web.Domain.OrderAggregate.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DatePaid")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("GuestUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MinimalClean.Architecture.Web.Domain.OrderAggregate.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("MinimalClean.Architecture.Web.Domain.ProductAggregate.Product", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CategorySlug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Instructor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsBestseller")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFlashSale")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Lessons")
                        .HasColumnType("int");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("OriginalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Rating")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("RatingCount")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<int>("Students")
                        .HasColumnType("int");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Lập Trình",
                            CategorySlug = "lap-trinh",
                            Description = "Khóa học React và TypeScript toàn diện, từ cơ bản đến nâng cao.",
                            Duration = "42 giờ",
                            Instructor = "Nguyễn Văn An",
                            IsBestseller = true,
                            IsFlashSale = false,
                            IsNew = false,
                            Language = "Tiếng Việt",
                            Lessons = 186,
                            Level = "Trung cấp",
                            Name = "React & TypeScript - Xây Dựng Ứng Dụng Thực Tế",
                            OriginalPrice = 1299000m,
                            Rating = 4.8m,
                            RatingCount = 2341,
                            Slug = "react-typescript-thuc-te",
                            Students = 15420,
                            Thumbnail = "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=400&h=225&fit=crop",
                            UnitPrice = 499000m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Lập Trình",
                            CategorySlug = "lap-trinh",
                            Description = "Học Python chuyên sâu về Data Science và Machine Learning.",
                            Duration = "60 giờ",
                            Instructor = "Trần Thị Bình",
                            IsBestseller = true,
                            IsFlashSale = true,
                            IsNew = false,
                            Language = "Tiếng Việt",
                            Lessons = 240,
                            Level = "Từ cơ bản",
                            Name = "Python for Data Science & Machine Learning",
                            OriginalPrice = 1599000m,
                            Rating = 4.9m,
                            RatingCount = 4521,
                            Slug = "python-data-science-ml",
                            Students = 28760,
                            Thumbnail = "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=225&fit=crop",
                            UnitPrice = 599000m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Thiết Kế",
                            CategorySlug = "thiet-ke",
                            Description = "Thiết kế giao diện người dùng chuyên nghiệp với Figma.",
                            Duration = "35 giờ",
                            Instructor = "Lê Hoàng Nam",
                            IsBestseller = false,
                            IsFlashSale = false,
                            IsNew = true,
                            Language = "Tiếng Việt",
                            Lessons = 145,
                            Level = "Từ cơ bản",
                            Name = "UI/UX Design với Figma - Từ Cơ Bản Đến Chuyên Nghiệp",
                            OriginalPrice = 999000m,
                            Rating = 4.7m,
                            RatingCount = 1876,
                            Slug = "uiux-figma-co-ban",
                            Students = 9845,
                            Thumbnail = "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=225&fit=crop",
                            UnitPrice = 399000m
                        });
                });

            modelBuilder.Entity("MinimalClean.Architecture.Web.Domain.CartAggregate.CartItem", b =>
                {
                    b.HasOne("MinimalClean.Architecture.Web.Domain.CartAggregate.Cart", null)
                        .WithMany("Items")
                        .HasForeignKey("CartId");
                });

            modelBuilder.Entity("MinimalClean.Architecture.Web.Domain.OrderAggregate.OrderItem", b =>
                {
                    b.HasOne("MinimalClean.Architecture.Web.Domain.OrderAggregate.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MinimalClean.Architecture.Web.Domain.CartAggregate.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MinimalClean.Architecture.Web.Domain.OrderAggregate.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
